# COLETA E MANIPULAÇÃO DE DADOS

## BIBLIOTECAS

In [57]:
import pandas as pd

## LEITURA DOS DADOS

In [58]:
dados = pd.read_csv('data/raw/dados_airbnb.csv', encoding='utf-8')

## CONHECENDO A BASE DE DADOS

In [59]:
## VISUALIZANDO QTD DE LINHAS E COLUNAS
dados.shape

(21286, 27)

In [60]:
## VISUALIZANDO AS PRIMEIRAS LINHAS
dados.head(10)

,id,listing_url,scrape_id,last_scraped,source,name,description,host_id,host_name,host_since,...,bedrooms,beds,price,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value
0,752318531145700331,https://www.airbnb.com/rooms/752318531145700331,20250624193519,2025-06-26,city scrape,Exceptional 2 Bed Copa 100m Beach,2 bedroom apartment 100 meters from Copacabana...,397106841,Jump In,2021-04-15,...,2.0,4.0,$507.00,3.00,5.00,4.00,2.00,3.00,5.00,3.00
1,1411843238290322081,https://www.airbnb.com/rooms/1411843238290322081,20250624193519,2025-06-27,city scrape,Tiny House Praia de Botafogo,welcome to your Apto in Botafogo!<br /><br />G...,156783825,Morada,2017-10-30,...,1.0,1.0,$215.00,4.82,4.91,4.91,5.00,4.91,5.00,4.82
2,1339188406746847719,https://www.airbnb.com/rooms/1339188406746847719,20250624193519,2025-06-27,city scrape,apartamento D Cs K,"Relax with the whole family, or with friends ...",674375308,Deisiana,2025-01-21,...,2.0,4.0,$90.00,5.00,5.00,5.00,5.00,5.00,4.80,5.00
3,1050604592912820183,https://www.airbnb.com/rooms/1050604592912820183,20250624193519,2025-06-28,city scrape,Renovated and charming close to Leblon beach!,"Apartment completely renovated, modern, super ...",508835814,Rio To Stay,2023-04-06,...,2.0,3.0,$769.00,4.75,4.88,4.84,4.88,4.94,4.88,4.69
4,1349515326730602111,https://www.airbnb.com/rooms/1349515326730602111,20250624193519,2025-06-26,city scrape,Ipanema_Errejota,This cozy 1 bedroom apartment located in the h...,198908935,FlÃ¡vio,2018-06-29,...,1.0,2.0,$351.00,4.82,4.82,4.91,4.82,5.00,4.73,4.73
5,1379137004786513676,https://www.airbnb.com/rooms/1379137004786513676,20250624193519,2025-06-27,previous scrape,"Vista PanorÃ¢mica de Copacabana, estÃºdio refo...",Renovated studio apartment with 1 bathroom and...,47013394,Bauhaus,2015-10-20,...,NaN,NaN,NaN,5.00,5.00,5.00,5.00,5.00,5.00,5.00
6,1200769557920683881,https://www.airbnb.com/rooms/1200769557920683881,20250624193519,2025-06-28,city scrape,Novo! Copacabana lindo 3 camas/ esq.da praia! ...,An elegant experience in this well-located pla...,321818201,Maria Luisa,2019-12-28,...,1.0,3.0,$352.00,5.00,4.90,5.00,4.70,4.90,4.60,4.90
7,692157484668621847,https://www.airbnb.com/rooms/692157484668621847,20250624193519,2025-06-26,city scrape,Hotel Barra da Tijuca quarto 14,Barra da Tijuca hotel room 14,297672983,Hotel,2019-09-24,...,1.0,1.0,$255.00,4.00,4.00,4.50,4.67,4.67,4.83,4.33
8,36357141,https://www.airbnb.com/rooms/36357141,20250624193519,2025-06-25,city scrape,EspaÃ§o aconchegante de fÃ¡cil acesso,"Amazing space, condominium owner with water ae...",143585640,Maicon Silva,2017-07-31,...,2.0,3.0,$300.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1016237339276614851,https://www.airbnb.com/rooms/1016237339276614851,20250624193519,2025-06-25,city scrape,Studio/vista mar/Ipanema,"Enjoy the clear, airy, quiet environment of th...",370324244,NaN,NaN,...,1.0,2.0,$540.00,4.00,4.67,4.33,3.67,3.33,5.00,3.67

In [61]:
## VISUALIZANDO AS INFORMAÇÕES DA BASE
# quantidade linhas e colunas
# quantidade de valores não nulos (preenchidos)
# tipo de dados em cada variável e quantidade
# tamanho da base de dados
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 21286 entries, 0 to 21285
Data columns (total 27 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   id                           21286 non-null  int64
 1   listing_url                  21286 non-null  str
 2   scrape_id                    21286 non-null  int64
 3   last_scraped                 21286 non-null  str
 4   source                       21286 non-null  str
 5   name                         21286 non-null  str
 6   description                  20766 non-null  str
 7   host_id                      21286 non-null  int64
 8   host_name                    20534 non-null  str
 9   host_since                   20495 non-null  str
 10  neighbourhood                8320 non-null   str
 11  neighbourhood_cleansed       21286 non-null  str
 12  latitude                     21286 non-null  str
 13  longitude                    21286 non-null  str
 14  room_type                    21286 non-null  str
 15  accommodates                 21286 non-null  int64
 16  bathrooms                    19465 non-null  float64
 17  bedrooms                     20919 non-null  float64
 18  beds                         19480 non-null  float64
 19  price                        19486 non-null  str
 20  review_scores_rating         16919 non-null  float64
 21  review_scores_accuracy       16914 non-null  float64
 22  review_scores_cleanliness    16915 non-null  float64
 23  review_scores_checkin        16915 non-null  float64
 24  review_scores_communication  16914 non-null  float64
 25  review_scores_location       16914 non-null  float64
 26  review_scores_value          16914 non-null  float64
dtypes: float64(10), int64(4), str(13)
memory usage: 4.4 MB

## SELEÇÃO E LIMPEZA DAS VARIÁVEIS (COLUNAS)

### LISTAR COLUNAS

In [62]:
dados.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'host_id', 'host_name', 'host_since', 'neighbourhood',
       'neighbourhood_cleansed', 'latitude', 'longitude', 'room_type',
       'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value'],
      dtype='str')

| Coluna                      | Conteúdo                                           |
|-----------------------------|----------------------------------------------------|
| id                          | Número de identificação das entradas               |
| listing_url                 | Link para o AirBnB                                 |
| last_scraped                | Data de quando os dados foram obtidos              |
| source                      | "Busca por cidade" ou "extração anterior"          |
| name                        | Nome da listagem no AirBnB                         |
| description                 | Detalhes do local da listagem                      |
| host_id                     | Id do dono do local                                |
| host_name                   | Nome do dono do local                              |
| host_since                  | Data de criação do perfil do dono do local         |
| neighbourhood               | O bairro da listagem                               |
| neighbourhood_cleansed      | O bairro da listagem                               |
| latitude                    | Latitude                                           |
| longitude                   | Longitude                                          |
| room_type                   | Tipo de Hospedagem                                 |
| accomodates                 | Quantas acomodações existem                        |
| bathroom                    | Número de banheiros                                |
| bedrooms                    | Número de quartos                                  |
| beds                        | Número de camas                                    |
| price                       | Preço                                              |
| review_scores_rating        | Nota das reviews                                   |
| review_scores_accuracy      | Precisão das notas                                 |
| review_scores_cleanliness   | Nota da limpeza                                    |
| review_scores_checkin       | Nota do CheckIn                                    |
| review_scores_location      | Nota do local                                      |
| review_scores_communication | Nota da comunicação com o dono                     |
| review_scores_value         | Nota da percepção do preço (Valor/Custo-Benefício) |

### SELECIONANDO AS VARIÁVEIS DE INTERESSE EM UM NOVO DATAFRAME

- Exclusão de variáveis que contém:
  - Apenas descrições textuais irrelevantes, como nome, descrição, anúncio, id de scrap...
  - Informações que não estão relacionadas ao imóvel e
  - dados duplicados
- Seleção de colunas para identificação e que podem ser relevantes para análise:
  - ``id`` e ``listing_url`` para referência,
  - ``neighbourhood_cleansed``, ``latitude`` e ``longitude`` para localização,
  - ``room_type``, ``accommodates``, ``bathrooms``, ``bedrooms``, ``beds`` e ``price`` para análise objetiva e
  - ``review_scores_rating`` e ``review_scores_value`` para análise comparativa com as avaliações

In [63]:
dados = dados.loc[:,  ['id', 'listing_url', 'neighbourhood_cleansed', 'latitude', 'longitude',
                        'room_type', 'accommodates', 'bathrooms', 'bedrooms', 'beds', 'price',
                        'review_scores_rating', 'review_scores_value'
                        ]]
dados.info()

<class 'pandas.DataFrame'>
RangeIndex: 21286 entries, 0 to 21285
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      21286 non-null  int64
 1   listing_url             21286 non-null  str
 2   neighbourhood_cleansed  21286 non-null  str
 3   latitude                21286 non-null  str
 4   longitude               21286 non-null  str
 5   room_type               21286 non-null  str
 6   accommodates            21286 non-null  int64
 7   bathrooms               19465 non-null  float64
 8   bedrooms                20919 non-null  float64
 9   beds                    19480 non-null  float64
 10  price                   19486 non-null  str
 11  review_scores_rating    16919 non-null  float64
 12  review_scores_value     16914 non-null  float64
dtypes: float64(5), int64(2), str(6)
memory usage: 2.1 MB

In [64]:
## VISUALIZANDO AS PRIMEIRAS LINHAS
dados.head(10)

,id,listing_url,neighbourhood_cleansed,latitude,longitude,room_type,accommodates,bathrooms,bedrooms,beds,price,review_scores_rating,review_scores_value
0,752318531145700331,https://www.airbnb.com/rooms/752318531145700331,Copacabana,"-22,96635","-43,17938",Entire home/apt,5,1.0,2.0,4.0,$507.00,3.00,3.00
1,1411843238290322081,https://www.airbnb.com/rooms/1411843238290322081,Botafogo,"-22,94533","-43,18163",Entire home/apt,2,1.0,1.0,1.0,$215.00,4.82,4.82
2,1339188406746847719,https://www.airbnb.com/rooms/1339188406746847719,Santa Cruz,"-22,9372198","-43,6966461",Entire home/apt,4,1.0,2.0,4.0,$90.00,5.00,5.00
3,1050604592912820183,https://www.airbnb.com/rooms/1050604592912820183,Leblon,"-22,981651797126293","-43,22314382772875",Entire home/apt,5,2.0,2.0,3.0,$769.00,4.75,4.69
4,1349515326730602111,https://www.airbnb.com/rooms/1349515326730602111,Ipanema,"-22,983108","-43,2026608",Entire home/apt,4,1.5,1.0,2.0,$351.00,4.82,4.73
5,1379137004786513676,https://www.airbnb.com/rooms/1379137004786513676,Copacabana,"-22,982367","-43,1901528",Entire home/apt,3,NaN,NaN,NaN,NaN,5.00,5.00
6,1200769557920683881,https://www.airbnb.com/rooms/1200769557920683881,Copacabana,"-22,984041","-43,1914755",Entire home/apt,4,1.0,1.0,3.0,$352.00,5.00,4.90
7,692157484668621847,https://www.airbnb.com/rooms/692157484668621847,Barra da Tijuca,"-23,0079","-43,30031",Private room,2,1.0,1.0,1.0,$255.00,4.00,4.33
8,36357141,https://www.airbnb.com/rooms/36357141,Recreio dos Bandeirantes,"-23,01587","-43,49285",Entire home/apt,4,3.0,2.0,3.0,$300.00,NaN,NaN
9,1016237339276614851,https://www.airbnb.com/rooms/1016237339276614851,Ipanema,"-22,986290236170653","-43,19501967358889",Entire home/apt,2,1.0,1.0,2.0,$540.00,4.00,3.67

## EXPLORAÇÃO DOS DADOS E AJUSTES

### VISUALIZAR VALORES ÚNICOS

In [65]:
dados['room_type'].unique()

<StringArray>
['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']
Length: 4, dtype: str

In [66]:
dados['price'].unique()

<StringArray>
[   '$507.00',    '$215.00',     '$90.00',    '$769.00',    '$351.00',
          nan,    '$352.00',    '$255.00',    '$300.00',    '$540.00',
 ...
  '$4,574.00',  '$3,480.00',  '$3,277.00',  '$2,582.00', '$14,628.00',
 '$10,400.00',  '$7,002.00',    '$849.00',  '$9,947.00',  '$2,697.00']
Length: 1883, dtype: str

Os "$" devem ser limpos e os preços padronizados

In [67]:
dados['bedrooms'].unique()

array([ 2.,  1., nan,  4.,  3.,  0.,  6.,  5., 10.,  7.,  9.,  8., 13.,
       16., 11., 26., 27., 14., 12.])

O valor 0 representa estúdios ou kitnets (lofts), onde não há divisão de paredes para o quarto.

In [68]:
dados['bathrooms'].unique()

array([ 1. ,  2. ,  1.5,  nan,  3. ,  6.5,  2.5,  0. ,  4. ,  7. ,  3.5,
        4.5,  0.5, 11. , 10. ,  5. ,  6. ,  5.5,  9. , 11.5,  8. , 12. ,
        7.5, 12.5,  8.5, 16. , 10.5, 15.5])

Os banheiros possuem uma contagem de 0.5, pois se referem à quantidades de lavabos (focados em pia e vaso sanitário, sem chuveiro)

In [69]:
# LISTAGEM DE BAIRROS
list(dados['neighbourhood_cleansed'].unique())

['Copacabana',
 'Botafogo',
 'Santa Cruz',
 'Leblon',
 'Ipanema',
 'Barra da Tijuca',
 'Recreio dos Bandeirantes',
 'Leme',
 'Flamengo',
 'Santa Teresa',
 'Centro',
 'IrajÃ¡',
 'JacarepaguÃ¡',
 'HumaitÃ¡',
 'Lagoa',
 'Laranjeiras',
 'JoÃ¡',
 'Camorim',
 'Catete',
 'Santo Cristo',
 'Guaratiba',
 'Jardim BotÃ¢nico',
 'Freguesia (JacarepaguÃ¡)',
 'GlÃ³ria',
 'Urca',
 'Catumbi',
 'Tijuca',
 'Vargem Pequena',
 'ItanhangÃ¡',
 'Campo Grande',
 'MÃ©ier',
 'PaquetÃ¡',
 'Anil',
 'Vaz Lobo',
 'Jardim Guanabara',
 'Piedade',
 'Pedra de Guaratiba',
 'SÃ£o Conrado',
 'HonÃ³rio Gurgel',
 'Vidigal',
 'SaÃºde',
 'GÃ¡vea',
 'Barra de Guaratiba',
 'Encantado',
 'Vila da Penha',
 'Taquara',
 'Rio Comprido',
 'Pechincha',
 'Rocinha',
 'Engenho de Dentro',
 'MaracanÃ£',
 'SÃ£o CristÃ³vÃ£o',
 'Coelho Neto',
 'Cosme Velho',
 'EstÃ¡cio',
 'Portuguesa',
 'Vila Valqueire',
 'Rocha Miranda',
 'Lins de Vasconcelos',
 'Cascadura',
 'Jardim Carioca',
 'Curicica',
 'Vila Isabel',
 'Pavuna',
 'MonerÃ³',
 'Vargem Grande',
 'Grumari',
 'Cordovil',
 'GardÃªnia Azul',
 'GrajaÃº',
 'HigienÃ³polis',
 'TauÃ¡',
 'PraÃ§a da Bandeira',
 'BrÃ¡s de Pina',
 'InhoaÃ\xadba',
 'Penha',
 'AndaraÃ\xad',
 'PraÃ§a Seca',
 'Del Castilho',
 'Freguesia (Ilha)',
 'Ã\x81gua Santa',
 'SÃ£o Francisco Xavier',
 'Vasco da Gama',
 'Riachuelo',
 'Bonsucesso',
 'Bangu',
 'InhaÃºma',
 'Senador Vasconcelos',
 'Jardim Sulacap',
 'Sampaio',
 'TomÃ¡s Coelho',
 'Rocha',
 'GaleÃ£o',
 'VigÃ¡rio Geral',
 'Alto da Boa Vista',
 'Gamboa',
 'Penha Circular',
 'Complexo do AlemÃ£o',
 'Madureira',
 'Cidade Nova',
 'Olaria',
 'Padre Miguel',
 'Campinho',
 'Cavalcanti',
 'Pilares',
 'Pitangueiras',
 'JacarÃ©',
 'Marechal Hermes',
 'Cachambi',
 'Bento Ribeiro',
 'BancÃ¡rios',
 'Praia da Bandeira',
 'ColÃ©gio',
 'Engenho Novo',
 'Cidade de Deus',
 'Jardim AmÃ©rica',
 'Todos os Santos',
 'Quintino BocaiÃºva',
 'Cosmos',
 'Zumbi',
 'SantÃ\xadssimo',
 'PaciÃªncia',
 'Benfica',
 'Engenho da Rainha',
 'Realengo',
 'Osvaldo Cruz',
 'AboliÃ§Ã£o',
 'Ramos',
 'Ricardo de Albuquerque',
 'Sepetiba',
 'Tanque',
 'Maria da GraÃ§a',
 'Vila Militar',
 'Cacuia',
 'Manguinhos',
 'Parque Anchieta',
 'CocotÃ¡',
 'Senador CamarÃ¡',
 'MagalhÃ£es Bastos',
 'Parada de Lucas',
 'Guadalupe',
 'Vicente de Carvalho',
 'MarÃ©',
 'TuriaÃ§Ãº',
 'GericinÃ³',
 'Anchieta',
 'Ribeira',
 'Mangueira',
 'Barros Filho']

### AJUSTE DE VARIÁVEIS (PREÇO, LOCALIZAÇÃO, BAIRROS)

#### REMOVER CARACTER ESPECIAL

In [70]:
dados['price'] = dados['price'].str.replace('$', '')
dados['price'] = dados['price'].str.replace(',', '')
dados['price'].unique()

<StringArray>
[  '507.00',   '215.00',    '90.00',   '769.00',   '351.00',        nan,
   '352.00',   '255.00',   '300.00',   '540.00',
 ...
  '4574.00',  '3480.00',  '3277.00',  '2582.00', '14628.00', '10400.00',
  '7002.00',   '849.00',  '9947.00',  '2697.00']
Length: 1883, dtype: str

Obs: encontramos preço nulo, devemos tratá-lo.

#### CONVERTE PRICE EM DECIMAL

In [71]:
dados['price'] = dados['price'].astype(float)
dados['price'].unique()

array([ 507.,  215.,   90., ...,  849., 9947., 2697.], shape=(1883,))

#### CONVERTE LATITUDE E LONGITUDE PARA VALOR

In [72]:
dados['latitude'] = dados['latitude'].str.replace(',', '.').astype(float)
dados['longitude'] = dados['longitude'].str.replace(',', '.').astype(float)

#### CORREÇÃO DE NOMES DE BAIRROS COM CARACTERES ESTRANHOS

In [73]:
nome_bairro = {
    'GÃ¡vea': 'Gávea',
    'MarÃ©': 'Maré',
    'TuriaÃ§Ãº': 'Turiaçu',
    'GericinÃ³': 'Gericinó',
    'Senador CamarÃ¡': 'Senador Camará',
    'MagalhÃ£es Bastos': 'Magalhães Bastos',
    'SaÃºde': 'Saúde',
    'CocotÃ¡': 'Cocotá',
    'Maria da GraÃ§a': 'Maria da Graça',
    'AboliÃ§Ã£o': 'Abolição',
    'PaciÃªncia': 'Paciência',
    'SantÃ\xadssimo': 'Santíssimo',
    'Quintino BocaiÃºva': 'Quintino Bocaiúva',
    'ColÃ©gio': 'Colégio',
    'BancÃ¡rios': 'Bancários',
    'Jardim AmÃ©rica': 'Jardim América',
    'TauÃ¡': 'Tauá',
    'JacarÃ©': 'Jacaré',
    'Complexo do AlemÃ£o': 'Complexo do Alemão',
    'TomÃ¡s Coelho': 'Tomás Coelho',
    'VigÃ¡rio Geral': 'Vigário Geral',
    'GaleÃ£o': 'Galeão',
    'HigienÃ³polis': 'Higienópolis',
    'PraÃ§a da Bandeira': 'Praça da Bandeira',
    'BrÃ¡s de Pina': 'Brás de Pina',
    'InhaÃºma': 'Inhaúma',
    'Ã\x81gua Santa': 'Água Santa',
    'PraÃ§a Seca': 'Praça Seca',
    'AndaraÃ\xad': 'Andaraí',
    'InhoaÃ\xadba': 'Inhoaíba',
    'IrajÃ¡': 'Irajá',
    'JacarepaguÃ¡': 'Jacarepaguá',
    'HumaitÃ¡': 'Humaitá',
    'JoÃ¡': 'Joá',
    'Jardim BotÃ¢nico': 'Jardim Botânico',
    'Freguesia (JacarepaguÃ¡)': 'Freguesia (Jacarepaguá)',
    'GlÃ³ria': 'Glória',
    'ItanhangÃ¡': 'Itanhangá',
    'MÃ©ier': 'Méier',
    'PaquetÃ¡': 'Paquetá',
    'SÃ£o Conrado': 'São Conrado',
    'HonÃ³rio Gurgel': 'Honório Gurgel',
    'MaracanÃ£': 'Maracanã',
    'SÃ£o CristÃ³vÃ£o': 'São Cristóvão',
    'EstÃ¡cio': 'Estácio',
    'MonerÃ³': 'Moneró',
    'GardÃªnia Azul': 'Gardênia Azul',
    'GrajaÃº': 'Grajaú',
    'SÃ£o Francisco Xavier': 'São Francisco Xavier'
}

dados['neighbourhood_cleansed'] = dados['neighbourhood_cleansed'].replace(nome_bairro)

  #### CONFERINDO AJUSTE

In [74]:
dados.info()
dados.head()

<class 'pandas.DataFrame'>
RangeIndex: 21286 entries, 0 to 21285
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      21286 non-null  int64
 1   listing_url             21286 non-null  str
 2   neighbourhood_cleansed  21286 non-null  str
 3   latitude                21286 non-null  float64
 4   longitude               21286 non-null  float64
 5   room_type               21286 non-null  str
 6   accommodates            21286 non-null  int64
 7   bathrooms               19465 non-null  float64
 8   bedrooms                20919 non-null  float64
 9   beds                    19480 non-null  float64
 10  price                   19486 non-null  float64
 11  review_scores_rating    16919 non-null  float64
 12  review_scores_value     16914 non-null  float64
dtypes: float64(8), int64(2), str(3)
memory usage: 2.1 MB

,id,listing_url,neighbourhood_cleansed,latitude,longitude,room_type,accommodates,bathrooms,bedrooms,beds,price,review_scores_rating,review_scores_value
0,752318531145700331,https://www.airbnb.com/rooms/752318531145700331,Copacabana,-22.966350,-43.179380,Entire home/apt,5,1.0,2.0,4.0,507.0,3.00,3.00
1,1411843238290322081,https://www.airbnb.com/rooms/1411843238290322081,Botafogo,-22.945330,-43.181630,Entire home/apt,2,1.0,1.0,1.0,215.0,4.82,4.82
2,1339188406746847719,https://www.airbnb.com/rooms/1339188406746847719,Santa Cruz,-22.937220,-43.696646,Entire home/apt,4,1.0,2.0,4.0,90.0,5.00,5.00
3,1050604592912820183,https://www.airbnb.com/rooms/1050604592912820183,Leblon,-22.981652,-43.223144,Entire home/apt,5,2.0,2.0,3.0,769.0,4.75,4.69
4,1349515326730602111,https://www.airbnb.com/rooms/1349515326730602111,Ipanema,-22.983108,-43.202661,Entire home/apt,4,1.5,1.0,2.0,351.0,4.82,4.73

In [75]:
list(dados['neighbourhood_cleansed'].unique())

['Copacabana',
 'Botafogo',
 'Santa Cruz',
 'Leblon',
 'Ipanema',
 'Barra da Tijuca',
 'Recreio dos Bandeirantes',
 'Leme',
 'Flamengo',
 'Santa Teresa',
 'Centro',
 'Irajá',
 'Jacarepaguá',
 'Humaitá',
 'Lagoa',
 'Laranjeiras',
 'Joá',
 'Camorim',
 'Catete',
 'Santo Cristo',
 'Guaratiba',
 'Jardim Botânico',
 'Freguesia (Jacarepaguá)',
 'Glória',
 'Urca',
 'Catumbi',
 'Tijuca',
 'Vargem Pequena',
 'Itanhangá',
 'Campo Grande',
 'Méier',
 'Paquetá',
 'Anil',
 'Vaz Lobo',
 'Jardim Guanabara',
 'Piedade',
 'Pedra de Guaratiba',
 'São Conrado',
 'Honório Gurgel',
 'Vidigal',
 'Saúde',
 'Gávea',
 'Barra de Guaratiba',
 'Encantado',
 'Vila da Penha',
 'Taquara',
 'Rio Comprido',
 'Pechincha',
 'Rocinha',
 'Engenho de Dentro',
 'Maracanã',
 'São Cristóvão',
 'Coelho Neto',
 'Cosme Velho',
 'Estácio',
 'Portuguesa',
 'Vila Valqueire',
 'Rocha Miranda',
 'Lins de Vasconcelos',
 'Cascadura',
 'Jardim Carioca',
 'Curicica',
 'Vila Isabel',
 'Pavuna',
 'Moneró',
 'Vargem Grande',
 'Grumari',
 'Cordovil',
 'Gardênia Azul',
 'Grajaú',
 'Higienópolis',
 'Tauá',
 'Praça da Bandeira',
 'Brás de Pina',
 'Inhoaíba',
 'Penha',
 'Andaraí',
 'Praça Seca',
 'Del Castilho',
 'Freguesia (Ilha)',
 'Água Santa',
 'São Francisco Xavier',
 'Vasco da Gama',
 'Riachuelo',
 'Bonsucesso',
 'Bangu',
 'Inhaúma',
 'Senador Vasconcelos',
 'Jardim Sulacap',
 'Sampaio',
 'Tomás Coelho',
 'Rocha',
 'Galeão',
 'Vigário Geral',
 'Alto da Boa Vista',
 'Gamboa',
 'Penha Circular',
 'Complexo do Alemão',
 'Madureira',
 'Cidade Nova',
 'Olaria',
 'Padre Miguel',
 'Campinho',
 'Cavalcanti',
 'Pilares',
 'Pitangueiras',
 'Jacaré',
 'Marechal Hermes',
 'Cachambi',
 'Bento Ribeiro',
 'Bancários',
 'Praia da Bandeira',
 'Colégio',
 'Engenho Novo',
 'Cidade de Deus',
 'Jardim América',
 'Todos os Santos',
 'Quintino Bocaiúva',
 'Cosmos',
 'Zumbi',
 'Santíssimo',
 'Paciência',
 'Benfica',
 'Engenho da Rainha',
 'Realengo',
 'Osvaldo Cruz',
 'Abolição',
 'Ramos',
 'Ricardo de Albuquerque',
 'Sepetiba',
 'Tanque',
 'Maria da Graça',
 'Vila Militar',
 'Cacuia',
 'Manguinhos',
 'Parque Anchieta',
 'Cocotá',
 'Senador Camará',
 'Magalhães Bastos',
 'Parada de Lucas',
 'Guadalupe',
 'Vicente de Carvalho',
 'Maré',
 'Turiaçu',
 'Gericinó',
 'Anchieta',
 'Ribeira',
 'Mangueira',
 'Barros Filho']

### TRATANDO NULOS E JUSTIFICATIVAS:
- O valor nulo não é usado nos algoritmos, por isso é importante tratá-los.  A forma como são tratados pode afetar a análise e a clusterização que faremos posteriormente com KMeans.
- Alguns algoritmos tratam nulos nativamente, mas outras formas de tratamento seriam:
  - Excluir o valor nulo;
  - Técnicas Estatísticas: moda, média, mediana, desvio padrão preenchendo os valores nulos com valores fixos;
  - Preencher com Algoritmo de Regressão para aprender padrões e prever os valores não preenchidos.
  - Modelo KNN para encontrar vizinhos similares e possíveis valores para preencher;
- O contexto sempre importa para esse tratamento. No nosso caso, as variáveis nulas que aparecem:
  - 1. Preço: Não podemos analisar mercado sem preço. Não serve para uma análise de precificação, pois não podemos inventar preço
        - 1.1: Vamos excluir apenas as linhas onde o price é nulo.
  - 2. Quartos, Camas e Banheiros: pode-se preencher com uma mediana baseada no tipo de quarto ``room_type`` sendo uma decisão ideal com contexto e segura para não faltar informação

In [76]:
dados = dados.dropna(subset=['price'])
dados['price'].unique()

array([ 507.,  215.,   90., ...,  849., 9947., 2697.], shape=(1882,))

In [77]:
colunas_para_preencher = ['bedrooms', 'beds', 'bathrooms']

for coluna in colunas_para_preencher:
    # Calcula a mediana de cada categoria (Entire home/apt, Private room, Shared room, Hotel room)
    mediana_por_tipo = dados.groupby('room_type')[coluna].transform('median')
    dados[coluna] = dados[coluna].fillna(mediana_por_tipo)

# Verificando se ainda há nulos
print(dados.isnull().sum())

id                           0
listing_url                  0
neighbourhood_cleansed       0
latitude                     0
longitude                    0
room_type                    0
accommodates                 0
bathrooms                    0
bedrooms                     0
beds                         0
price                        0
review_scores_rating      3889
review_scores_value       3894
dtype: int64

# SALVAR BASE
- Caso ocorra algum problema, evitar reprocessamento demorado, para voltar o projeto de onde parou

In [78]:
## SALVANDO EM CSV
dados.to_csv('data/processed/dados_airbnb_processados.csv', encoding='utf-8', index=False)